name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 6 * * *' # Run at 0600 daily
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ae22098dd6a544e02c5e18e
